# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grand Share Auto Accessories
email: grandshare.pc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Grand Share Auto Accessories
address_line: 25-A, Jalan Siam, 10400 Pulau Pinang, Malaysia
telephone_number: +604-2288782, +604-2280401
fax_number: +604-2265188
company_email: grandshare.pg@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3972.0241501641526!2d100.31984531407991!3d5.413292336575366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ac3bed3dd482d%3A0xed63822806a05480!2sGrand+Share+Auto+Accessories!5e0!3m2!1sen!2smy!4v1522898835225

# Social Link
facebook_link: 
twitter_link: 
linkedin_link: 
googleplus_link: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grand Share Auto Accessories
email: grandshare.pc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Grand Share Auto Accessories
address_line: 25-A, Jalan Siam, 10400 Pulau Pinang, Malaysia
telephone_number: +604-2288782, +604-2280401
fax_number: +604-2265188
company_email: grandshare.pg@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3972.0241501641526!2d100.31984531407991!3d5.413292336575366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ac3bed3dd482d%3A0xed63822806a05480!2sGrand+Share+Auto+Accessories!5e0!3m2!1sen!2smy!4v1522898835225

# Social Link
twitter_link:
linkedin_link:
googleplus_link:
facebook_link: https://www.facebook.com/grandshareauto/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/